name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  VERSION: 'x'


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4    

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        registry: ghcr.io
        username: bognarpal
        password: ${{secrets.GHCR_TOKEN}}      
    
    - name: Build the Docker image
      run: |
        $VERSION = $(date +%s)
        docker build . --file Dockerfile --tag ghcr.io/bognarpal/azure-webapp-test:${{ env.VERSION }} --tag ghcr.io/bognarpal/azure-webapp-test:latest
        docker push ghcr.io/bognarpal/azure-webapp-test:latest
        docker push ghcr.io/bognarpal/azure-webapp-test:$VERSION

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'bp-test-cicd'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_71fba68f48cf4f3187c9611020515e67 }}
        images: ghcr.io/bognarpal/azure-webapp-test:${{ env.VERSION }}
